########################################################
# creates postgres sql database image and pgadmin4 image
# login db: postgres:postgres hostname: postgres
# login pgadmin: admin@developer-blog.net:admin port 5555
########################################################
version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: codemuseum-postgres

    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codemuseum-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: codemuseum-pgadmin
    depends_on:
      - postgres
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

  dbeaver:
    image: dbeaver/dbeaver-ce:latest
    depends_on:
      - postgres
    environment:
      - DBEAVER_VERSION=21.1.0

    volumes:
      - ./dbeaver-config:/home/dbeaver/.dbeaver4

volumes:
  postgres-data:
